# `AA` - Workshop 02

In this tutorial we will introduce the concept of python libraries and cover a first such library - NumPy.

We will go through the following:

- Python dictionary and lists comprehensions
- Introduction to the concept of `Python Libraries`
- Introduction to `NumPy`

## Python dictionary comprehensions

Dictionary comprehension is a method for transforming one dictionary into another dictionary. During this transformation, items within the original dictionary can be conditionally included in the new dictionary and each item can be transformed as needed. Dictionary comprehension is a powerful concept and can be used to substitute `for loops` and `lambda functions`. However, not all `for loop` can be written as a dictionary comprehension but all dictionary comprehension can be written with a `for loop`. (We will talk about `lambda functions` in future workshops).

A good list comprehension can make your code more expressive and thus, easier to read. The key with creating comprehensions is to not let them get so complex that your head spins when you try to decipher what they are actually doing. Keeping the idea of "easy to read" alive.

the general template you can follow for dictionary comprehension in Python:

`dict_variable = {key:value for (key,value) in dictonary.items()}`

In [1]:
dict1 = {'a':1, 'b':2, 'c':3, 'd':4}

Remeber that with `items()` method you can access each key-value pair in a dictunary. You can access the values and keys in a dictionary by using `values()` and `keys()`, respectively.

In [2]:
print(dict1.items())
print(dict1.values())
print(dict1.keys())

dict_items([('a', 1), ('b', 2), ('c', 3), ('d', 4)])
dict_values([1, 2, 3, 4])
dict_keys(['a', 'b', 'c', 'd'])


Here are some examples of dictionary comprehensions

In [71]:
{k:v for k in ['a','b'] for v in [3,4]}

{'a': 4, 'b': 4}

In [3]:
# Power 2 each value in the dictionary

new_dict1 = {k:v**2 for (k,v) in dict1.items()}
print(double_dict1)

{'a': 1, 'b': 4, 'c': 9, 'd': 16}


In [4]:
#Changing the keys of the original dictionary

dict1_keys = {k+'a':v for (k,v) in dict1.items()}
print(dict1_keys)

{'aa': 1, 'ba': 2, 'ca': 3, 'da': 4}


Consider the following problem, where you want to create a new dictionary with even numbers in a range of 0-10 and it's value is the square of the number. One solution is to use a `for` loop. Another solution is to use dictionary comprehension method as follows

In [5]:
new_dict = {n:n**2 for n in range(10) if n%2 == 0}

print(new_dict)

{0: 0, 2: 4, 4: 16, 6: 36, 8: 64}


**Exercise:** create a distionary that detects whether the values of the following dictionary are even or odd numbers.

In [2]:
dict3 = {'a': 1, 'b': 2, 'c': 3, 'd': 4, 'e': 5, 'f':6}

# Your code 
new_dict3 = {k:('even' if v%2==0 else 'odd') for (k,v) in dict3.items()}
new_dict3

{'a': 'odd', 'b': 'even', 'c': 'odd', 'd': 'even', 'e': 'odd', 'f': 'even'}

You can do the same operation with python lists

In [7]:
ls1 = [i for i in range(10)]
ls1

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [8]:
ls2 = [str(i**2) for i in range(10) if i%3==0 ]
print(ls2)

['0', '9', '36', '81']


In [9]:
quote = "life, uh, finds a way"
unique_vowels = {i for i in quote if i in 'aeiou'}
vowels = [i for i in quote if i in 'aeiou']
print(unique_vowels)
print(vowels)

{'a', 'u', 'e', 'i'}
['i', 'e', 'u', 'i', 'a', 'a']


## `Python Libraries`

**Introduction to Libraries**

A library (or module, or package) is a Python object with arbitrarily named attributes that you can bind and reference. Simply, a module is a file consisting of Python code. A module can define functions, classes and variables. A module can also include runnable code.

You can use any Python source file as a module by executing an import statement in some other Python source file. The import has the following syntax:


```
import <module name>
```

By convention it is common to name modules so they can be called by entering an abreviated name. This is effectively importing the module in the same way that `import <module name>` will do, with the only difference of it being available as ` <module name abbreviation>`. In the case of `numpy`, for example, the abbreviation `np`is used.

```
import <module name> as <module name abbreviation>
```


In [10]:

import numpy as np


**Adding/Installing Libraries**

To add Python libraries to your installation you can use the `conda` package manager that we have installed in the last workshop. Alternatively you can also use the `pip` package manager. The quickest way to do so is via a terminal:

* If you are on a **Windows** computer, use the "Anaconda Command Prompt" from the Start menu. 
* On a **Mac**, start up the "Terminal". 
* In **Linux**, use any of the terminals available.


The gerneral command syntax is the following:

```
conda install <package name>
```

If you are looking for a specific package but are unsure of the exact command line name do a quick google search and/or check the [Anaconda Cloud](https://anaconda.org). Another approach to find the exact name of a package before installation is using the conda search command in terminal; the syntax is the following:

```
conda search <name>
```


**Relevant Libraries for this course**

There is a large variety of open source libraries available in Python. Below is a list of some of the most relevant ones for data science, which will be covered in this course.

* Selected data science libraries

    * Data Analysis and Processing
    >* Pandas (pd)
    >* Numpy (np)
    * Visualization        
    >* matplotlib and pyplot (plt)
    >* seaborn (sns)
    * Models and methods
    >* Scikit Learn (sklearn)
    >* statsmodels

**Exercise**: Install Scikit Learn on your machine using the command `conda install -c anaconda scikit-learn`. Afterwards import the library here as sklearn.

In [11]:
# Your code here

import sklearn



---

## `NumPy`

NumPy is the fundamental package for scientific computing with Python. It contains among other things:

- A powerful N-dimensional array object
- Sophisticated (broadcasting) functions
- Tools for integrating C/C++ and Fortran code
- Useful linear algebra, Fourier transform, and random number capabilities

Besides its obvious scientific uses, NumPy can also be used as an efficient multi-dimensional container of generic data. Arbitrary data-types can be defined. This allows NumPy to seamlessly and speedily integrate with a wide variety of databases.

NumPy’s main object is the homogeneous multidimensional array. It is a table of elements (usually numbers), all of the same type, indexed by a tuple of positive integers. In NumPy dimensions are called axes. The number of axes is rank.

In today's short overview tutorial we will cover the following:

1. **Creating NumPy Arrays**
1. **Modifying (manipulating) NumPy Arrays**
1. **NumPy Array Oprations**

Let's get started...

In [12]:
import numpy as np

### Creating NumPy Arrays

First, we can use `np.array` to create arrays from python lists. Unlike the Python lists, **NumPy is constrained to arrays that all contain the same type**. If types don't match, NumPy will upcast if possible. 

In [13]:
A = np.array([1,2,3,4,5])
A

array([1, 2, 3, 4, 5])

In [14]:
B = np.array([3.1, 5, 4, 6])
B

array([3.1, 5. , 4. , 6. ])

In [15]:
D =np.array([1,2,'a',3])
D

array(['1', '2', 'a', '3'], dtype='<U21')

In the above output the `U` which denotes a Unicode dtype and the `#` denotes the number of elements it can hold. This may be different in different platforms though.

In [16]:
#dtype('<U21')  # 64bit Linux
D.dtype

dtype('<U21')

In [17]:
D.dtype.type  # The type object used to instantiate a scalar of this data-type.

numpy.str_

In [18]:
D.dtype.itemsize #4*21

84

Read more info in greater details about string types and other datatype objects in the [numpy documentation](https://docs.scipy.org/doc/numpy-1.14.0/reference/arrays.dtypes.html#data-type-objects-dtype).

If we want to explicitly set the data type of the resulting array, we can use the `dtype` keyword.

In [19]:
C = np.array([1,2,3,8],dtype = float)
print (C)

[1. 2. 3. 8.]


Other examples of creating arrays using np functions:

In [20]:
# create vector of length 5 filled with zeros
E = np.zeros(5,dtype = float)

# create 2x4 matrix of ones (float)
F = np.ones((2,4), dtype= float)

# create vector from 0-12 in steps of 2
G = np.arange(0,12,2)

# create vector from 0 to 1 with five equally (linearly) spaced elements 
H = np.linspace(0,1,5)

# create a 2x2 matrix with random floats in the half-open interval [0.0, 1.0)
I = np.random.random((2,2))

#Return random integers from 0 (inclusive) to 10 (exclusive) of size (4,3,2)
J = np.random.randint (0,10,(4,3,2))

print("E =", E,
      "\n\nF =", F, 
      "\n\nG =", G, 
      "\n\nH =", H, 
      "\n\nI =", I, 
      "\n\nJ =", J)

E = [0. 0. 0. 0. 0.] 

F = [[1. 1. 1. 1.]
 [1. 1. 1. 1.]] 

G = [ 0  2  4  6  8 10] 

H = [0.   0.25 0.5  0.75 1.  ] 

I = [[0.05279506 0.53240636]
 [0.91432675 0.25184743]] 

J = [[[3 6]
  [6 7]
  [7 0]]

 [[5 0]
  [8 6]
  [9 6]]

 [[4 3]
  [1 1]
  [0 1]]

 [[5 0]
  [1 6]
  [0 9]]]


**Exercise**: Define a few additional NumPy Arrays using some or all of the commands introduced above

In [21]:
# Your code here








### Modifying (manipulating) NumPy Arrays

Data manipulation in Python is nearly synonymous with NumPy array manipulation. We will cover a few categories of basic array manipulations here:
- **Attributes of arrays**: Determinig the size, shape, memory consumption and data type of arrays.
- **Indexing of arrays**: Getting and setting the value of indivisual array elements.
- **Slicing of arrays**: Getting and setting smaller subarrays within a larger array.
- **Reshaping of arrays**: Changing the shape of a given array.
- **Joining and splitting of arrays**: Combining multiple arrays into one, and splitting one array into many.

#### NumPy Array Attributes:
In the following some examples on attributes are presented.

In [22]:
# returns dimension
print("E ndim: ", E.ndim)

# returns shape in form (#row,#col)
print("F sahpe: " , F.shape)

# returns size (i.e. no of elements)
print("J size: ", J.size)

# returns data type
print("H dtype: ", H.dtype)

# returns length of one array element in bytes
print("itemsize: ", I.itemsize," bytes")

# returns total bytes consumed by the elements of the array
print("nbytes:  ", I.nbytes, "bytes")

E ndim:  1
F sahpe:  (2, 4)
J size:  24
H dtype:  float64
itemsize:  8  bytes
nbytes:   32 bytes


#### NumPy Array Indexing:
In the following some examples on attributes are presented.

Accessing single elements:

In [23]:
A

array([1, 2, 3, 4, 5])

In [24]:
A[-2]

4

In [25]:
print ("The 4th element of A is {}". format(A[3]))
print ("The last element of A is {}". format(A[-1])) # index from the back

The 4th element of A is 4
The last element of A is 5


In a multidimensional array (i.e. a matrix), you access items using a comma-seperated tuple of indices.

In [26]:
I

array([[0.05279506, 0.53240636],
       [0.91432675, 0.25184743]])

In [27]:
I[1,1]

0.25184742647046343

In [28]:
print ("The first element of I is {}". format(I[0,0]))  #array[row,column]
print ("The last element of I is {}". format(I[1,1]))   #array[row,column]

The first element of I is 0.05279505509015592
The last element of I is 0.25184742647046343


**Exercise**: Play around with the techniques and commands introduced above and apply them to the previously defined arrays for practice

In [29]:
# Your code here








#### NumPy Array Slicing:

**One-dimensional arrays**

Just as we can use square brakets to access individual array elements, we can also use them to access subarrays with the slice notation, marked by the colon `:` character. The syntax is as follow:
` X[start (incl.):stop (excl.):step]`

In [30]:
G

array([ 0,  2,  4,  6,  8, 10])

In [31]:
# item 3 and 4
print ("middle subarray:", G[2:4])

# item 1 to 4(excl.)
print("First 4 elemnts:", G[:5])

# last 3
print("Last 3 elements:", G[-3:] )

# first element and every second from there
print("Every other element:", G[::2])


print ("All elements reversed:", G[::-1])

middle subarray: [4 6]
First 4 elemnts: [0 2 4 6 8]
Last 3 elements: [ 6  8 10]
Every other element: [0 4 8]
All elements reversed: [10  8  6  4  2  0]


**Multi-dimensional arrays**

Multi-dimensional slices work in the same way, with multiple slices seperated by commas. The command is `X[slice row, slice column]`

In [32]:
# create a multi-dimensional array
K = np.random.randint(0,20, (3,4))
K

array([[12,  7,  3,  3],
       [11, 17, 13,  9],
       [14, 11,  2,  9]])

In [33]:
print ("The first two rows and the first three column: \n", K[:2,:3])

The first two rows and the first three column: 
 [[12  7  3]
 [11 17 13]]


In [34]:
print("All rows and every other column:\n", K[:,::2])

All rows and every other column:
 [[12  3]
 [11 13]
 [14  2]]


In [35]:
print("Reversed:\n",K[::-1,::-1] )

Reversed:
 [[ 9  2 11 14]
 [ 9 13 17 11]
 [ 3  3  7 12]]


**Exercise**: Familiarize yourself with indexing by attempting some indexing techniques on the arrays defined above

In [36]:
# Your code here








#### NumPy Array Reshaping:

Another useful type of operation is reshaping of arrays. The most flexible way of doing this is with the reshape method. Note that for this to work, the size of the initial array must match the size of the reshaped array.

In [37]:
# return evenly spaced values within a given interval
Y = np.arange(1,25)
Y

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [38]:
len(Y)

24

In [39]:
# we can re-shape this array into any shape with 24 elements

Y.reshape(6,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

#### NumPy Array Concatenation and Splitting

All of the preceding routines worked on single arrays. It's also possible to combine multiple arrays into one, and to conversely split a single array into multiple arrays.

**Concatination of arrays**

Concatenation, or joining of two arrays in NumPy, is primarily accomplished using the routine `np.concatenate`. Additionally `np.vstack`, and `np.hstack` may be used.

In [40]:
P = np.array([1,2,3])
Q = np.array([4,5,6])
np.concatenate((P,Q))

array([1, 2, 3, 4, 5, 6])

In [41]:
R = np.array([[3,5,7],[1,3,5]])
S = np.array([[2,4,2],[0,9,8]])

In [42]:
R

array([[3, 5, 7],
       [1, 3, 5]])

In [43]:
S

array([[2, 4, 2],
       [0, 9, 8]])

In [44]:
#The axis along which the arrays will be joined.
print (np.concatenate((R,S), axis = 0))

[[3 5 7]
 [1 3 5]
 [2 4 2]
 [0 9 8]]


For working with arrays of mixed dimensions, it can be more practical to use the `np.vstack` (vertical stack) and `np.hstack` (horizontal stack) functions:

In [45]:
R = np.array([[3,5,7],[1,3,5]])
S = np.array([[2,4,2],[0,9,8]])

In [46]:
# stack row-wise
np.vstack((R,S))

array([[3, 5, 7],
       [1, 3, 5],
       [2, 4, 2],
       [0, 9, 8]])

In [47]:
# stack column-wise
np.hstack((R,S))

array([[3, 5, 7, 2, 4, 2],
       [1, 3, 5, 0, 9, 8]])

**Splitting of arrays**

The opposite of concatenation is splitting, which is implemented by the functions `np.split`, `np.hsplit`, and `np.vsplit`. For each of these, we can pass a list of indices giving the split points:

In [51]:
# Devides the x array to 4 equal subarrays.
x = np.array([2,4,6,7,8,9,1,3,11,35,55,34])
np.split(x,4)

[array([2, 4, 6]), array([7, 8, 9]), array([ 1,  3, 11]), array([35, 55, 34])]

In [52]:
x1, x2, x3, x4 = np.split(x,4)
print(x1, x2, x3, x4)

[2 4 6] [7 8 9] [ 1  3 11] [35 55 34]


In [53]:
x1

array([2, 4, 6])

In [54]:
Z = np.arange(16).reshape((4, 4))
Z

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [55]:
#Splits an array into multiple sub-arrays vertically (row-wise).
upper, lower = np.vsplit(Z, 2)
print("upper: \n",upper)
print("lower: \n",lower)

upper: 
 [[0 1 2 3]
 [4 5 6 7]]
lower: 
 [[ 8  9 10 11]
 [12 13 14 15]]


In [56]:
#Splits an array into multiple sub-arrays horizontally (column-wise).
left, right = np.hsplit(Z, 2)
print("left: \n",left)
print("right: \n",right)

left: 
 [[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
right: 
 [[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


**Exercise**: Create a few arrays and concantenate them, afterwards split them to arrive at the original arrays

In [57]:
# Your code here








### NumPy Array Operations

Numpy also allows for **element-wise** as well as linear algebra **matrix-type** operations, which are a key component of scientific computing tasks.

In [58]:
A = np.array([1,2,3,4])
B = np.array([9,3,-9,6])

In [59]:
A

array([1, 2, 3, 4])

In [60]:
B

array([ 9,  3, -9,  6])

**Element-wise operations**

In [61]:
# element-wise addition

C=A+B
C

array([10,  5, -6, 10])

In [62]:
# element-wise substraction

D=A-B
D

array([-8, -1, 12, -2])

In [63]:
# element-wise multiplication

E=A*B
E

array([  9,   6, -27,  24])

In [64]:
# element-wise division

F=A/B
F

array([ 0.11111111,  0.66666667, -0.33333333,  0.66666667])

**Matrix operations**

In [65]:
M = np.arange(10).reshape(2,5)
M

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [66]:
N = np.random.randint(1,10,10).reshape(2,5)
N

array([[2, 4, 7, 7, 7],
       [5, 5, 3, 9, 7]])

In [67]:
# Note: we are performing a matrix multiplication on two 2x5 matrices, which is not possible
M@N

ValueError: shapes (2,5) and (2,5) not aligned: 5 (dim 1) != 2 (dim 0)

In [68]:
# We can transpose one of the matrices to obtain a 5x2 matrix
N.T

array([[2, 5],
       [4, 5],
       [7, 3],
       [7, 9],
       [7, 7]])

In [69]:
# The operation works
M@N.T

array([[ 67,  66],
       [202, 211]])

**Final note**
To add table of content to your jupyter notebook, you need to install `nbextension` available on https://github.com/minrk/ipython_extensions.

---